<a href="https://colab.research.google.com/github/Deepakkmyadav/Time-series/blob/main/Pytorch%20Arithmatic%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import torch
import torch

In [5]:
your_first_tensor=torch.rand(2,3)

In [6]:
# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

In [8]:
# Print the values of the tensor and its shape
print(your_first_tensor )
print(tensor_size)

tensor([[0.6801, 0.2816, 0.5843],
        [0.3084, 0.2256, 0.4591]])
torch.Size([2, 3])


In [10]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

In [13]:
print(identity_tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [15]:
# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)


matrices_multiplied_normal = tensor_of_ones* identity_tensor
print(matrices_multiplied_normal)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [16]:
# Initialize tensors x, y and z
x = torch.rand(1000,1000)
y = torch.rand(1000,1000)
z = torch.rand(1000,1000)

# Multiply x with y
q = torch.matmul(x,y)

# Multiply elementwise z with q
f = q*z

mean_f = torch.mean(f)
print(mean_f)

tensor(125.1597)


In [17]:
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

q = x + y
f = q * z

f.backward()
print("Gradient of z is: " + str(z.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of x is: " + str(x.grad))



Gradient of z is: tensor(1.)
Gradient of y is: tensor(5.)
Gradient of x is: tensor(5.)
